# ...existing code...
INSTALLED_APPS = [
    # ...existing code...
    'django.contrib.humanize',
    # ...existing code...
]
TEMPLATES = [
    {
        # ...existing code...
        'OPTIONS': {
            'context_processors': [
                # ...existing code...
                'shop_app.context_processors.cart_count',
            ],
        },
    },
]
# ...existing code...
